// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1E5rmoeYhoIdPWbAiuseLHuc_VfwYbpo',
    appId: '1:220858181813:web:9fbd821247d4e758ac76fc',
    messagingSenderId: '220858181813',
    projectId: 'tminder-8a22e',
    authDomain: 'tminder-8a22e.firebaseapp.com',
    storageBucket: 'tminder-8a22e.appspot.com',
    measurementId: 'G-81EQ4STWNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCees1vwWS7ai-HKNtpiHyQqx5nfl36Khc',
    appId: '1:220858181813:android:dc164a5b7007212dac76fc',
    messagingSenderId: '220858181813',
    projectId: 'tminder-8a22e',
    storageBucket: 'tminder-8a22e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM3iLVYrYZslqHGuBsuoTzZu72jKC9fDM',
    appId: '1:220858181813:ios:8a7dba93eb4b6079ac76fc',
    messagingSenderId: '220858181813',
    projectId: 'tminder-8a22e',
    storageBucket: 'tminder-8a22e.appspot.com',
    iosBundleId: 'com.mosalahdev.tminderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM3iLVYrYZslqHGuBsuoTzZu72jKC9fDM',
    appId: '1:220858181813:ios:22dbbbfefed2bb97ac76fc',
    messagingSenderId: '220858181813',
    projectId: 'tminder-8a22e',
    storageBucket: 'tminder-8a22e.appspot.com',
    iosBundleId: 'com.example.tmartExpiryDate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1E5rmoeYhoIdPWbAiuseLHuc_VfwYbpo',
    appId: '1:220858181813:web:978fe54203852e08ac76fc',
    messagingSenderId: '220858181813',
    projectId: 'tminder-8a22e',
    authDomain: 'tminder-8a22e.firebaseapp.com',
    storageBucket: 'tminder-8a22e.appspot.com',
    measurementId: 'G-T9Q9MPDMQZ',
  );
}
